name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Install Packages and Build Application
        run: |
          npm install -g @vue/cli
          npm install
          npm run build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: click-counter
          BRANCH: main
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
